/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 17-Mar-2024 16:08:42
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型
 * 分子 长度  : 7
 * 分母 长度  : 7
 * 稳定     : 是
 * 线性相位   : 否
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Matlab\extern\include\tmwtypes.h 
 */
const int NL = 7;
const real64_T b[7] = {
  0.0006230071815402,                 0,-0.001869021544621,                 0,
   0.001869021544621,                 0,-0.0006230071815402
};
const int DL = 7;
const real64_T a[7] = {
                   1,    -5.62714525801,    13.21228238623,   -16.56970176617,
      11.70713987005,   -4.418572558341,   0.6959973817517
};
