/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 17-Mar-2024 15:58:47
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型
 * 分子 长度  : 3
 * 分母 长度  : 3
 * 稳定     : 是
 * 线性相位   : 否
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Matlab\extern\include\tmwtypes.h 
 */
const int NL = 3;
const real64_T b[3] = {
    0.08317909958406,                 0, -0.08317909958406
};
const int DL = 3;
const real64_T a[3] = {
                   1,   -1.829926575522,   0.8336418008319
};
