/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 17-Mar-2024 15:28:41
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型
 * 分子 长度  : 5
 * 分母 长度  : 5
 * 稳定     : 是
 * 线性相位   : 否
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Matlab\extern\include\tmwtypes.h 
 */
const int NL = 5;
const real64_T NUM[5] = {
   0.007295260049982,                 0, -0.01459052009996,                 0,
   0.007295260049982
};
const int DL = 5;
const real64_T DEN[5] = {
                   1,   -3.779922355034,    5.380925806248,   -3.421326882563,
     0.8203382428819
};
