/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 17-Mar-2024 16:20:04
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型
 * 分子 长度  : 5
 * 分母 长度  : 5
 * 稳定     : 是
 * 线性相位   : 否
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Matlab\extern\include\tmwtypes.h 
 */
const int NL = 5;
const real64_T b[5] = {
   0.003348937448482,                 0,-0.006697874896963,                 0,
   0.003348937448482
};
const int DL = 5;
const real64_T a[5] = {
                   1,   -3.821042153824,    5.485971130482,   -3.508063833372,
     0.8431538806333
};
